variables:
  - group: buildspec-gitsecrets

trigger:
  branches:
    include:
      - staging
  paths:
    include:
      - 2021-05-11-ADO/vnet

stages:
  - stage: Scan repo
    displayName: Setup
    env:
      git-credential-helper: yes
    jobs:
    # Install
      - job: install
        steps:
          - script:
            displayName: "Install requirements"
              - echo "in the install phase"
              - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
    # Build
      - job: build
        steps:
          - script:
            displayName: "Build"
            - echo "Build started on $(date)"
            - git clone https://github.com/awslabs/git-secrets
            - cd git-secrets
            - make install
            - cd $CODEBUILD_SRC_DIR
            - git clone https://git-codecommit.us-east-2.amazonaws.com/v1/repos/$CODECOMMIT_REPO_NAME
            - cd $CODECOMMIT_REPO_NAME && ls -lrt
            - git secrets --install
            - git secrets --register-aws
            ## Adding additional patterns, for example password
            #- git secrets --add password\s*=\s*.+
            - git secrets --scan --recursive
            - echo "Build completed on $(date)"
# artifacts:
#   type: zip
#   files: '**/*'